FROM ubuntu:22.04
MAINTAINER Kirill kirill.tomorrow@gmail.com

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update
RUN apt-get -y upgrade

RUN apt-get install -y unzip
RUN apt-get install -y build-essential
RUN apt-get install -y gdb
RUN apt-get install -y git
RUN apt-get install -y libfmt-dev
RUN apt-get install -y wget

RUN wget https://github.com/Kitware/CMake/releases/download/v3.27.5/cmake-3.27.5-Linux-x86_64.sh \
      -q -O /tmp/cmake-install.sh \
      && chmod u+x /tmp/cmake-install.sh \
      && mkdir /usr/bin/cmake \
      && /tmp/cmake-install.sh --skip-license --prefix=/usr/bin/cmake \
      && rm /tmp/cmake-install.sh

ENV PATH="/usr/bin/cmake/bin:${PATH}"

RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get install -y python-is-python3
RUN apt-get install -y libblas-dev
RUN apt-get install -y libopenblas-dev
RUN apt-get install -y libfftw3-dev 
RUN apt-get install -y libatlas-base-dev
RUN apt-get install -y liblapacke-dev
RUN apt-get install -y liblapack-dev
RUN apt-get install -y libboost-all-dev
RUN apt-get install -y libopencv-core4.5d
RUN apt-get install -y libopencv-imgproc4.5d
RUN apt-get install -q -y libopencv-dev
RUN apt-get install -y libopencv-highgui4.5d
RUN apt-get install -y libopencv-highgui-dev
RUN apt-get install -y libhdf5-dev
RUN apt-get install -y libjson-c-dev
RUN apt-get install -y libx11-dev
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y openjdk-17-jdk
RUN apt-get install -y ninja-build
RUN apt-get install -y gnuplot
RUN apt-get install -y vim
RUN apt-get install -y python3-venv
RUN apt-get install -y libcpuinfo-dev
RUN apt-get install -y libspdlog-dev


RUN pip install pyyaml
RUN pip install typing
RUN pip install typing_extensions
RUN pip install optuna
RUN pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu
RUN pip install transformers
RUN pip install mlflow==2.15.0


RUN mkdir development
ADD checkout_lib.sh /development
RUN chmod 777 /development/checkout_lib.sh
ADD install_lib.sh /development
RUN chmod 777 /development/install_lib.sh
ADD install_env.sh /development
RUN chmod 777 /development/install_env.sh
ADD install_android.sh /development
RUN chmod 777 /development/install_android.sh
ADD install_lib_custom.sh /development
RUN chmod 777 /development/install_lib_custom.sh

WORKDIR /development
RUN ./install_env.sh
RUN ./install_android.sh

